In [9]:
# 1. Write a Python Program to Add Two Matrices?

import numpy as np

mat1 = np.array([[1,4,6],
        [7,5,88],
        [8,5,77]])
mat2 = np.array([[12,43,74],
        [5,8,3],
        [8,9,9]])

Matsum = np.add(mat1,mat2)
Matsum

array([[13, 47, 80],
       [12, 13, 91],
       [16, 14, 86]])

In [11]:
# 2. Write a Python Program to Multiply Two Matrices?

mat1 = np.array([[1,4,6],
        [7,5,88],
        [8,5,77]])
mat2 = np.array([[12,43,74],
        [5,8,3],
        [8,9,9]])

Matsum = np.multiply(mat1,mat2)
Matsum

array([[ 12, 172, 444],
       [ 35,  40, 264],
       [ 64,  45, 693]])

In [13]:
# 3. Write a Python Program to Transpose a Matrix?
mat1 = np.array([[1,4,6],
        [7,5,88],
        [8,5,77]])
mat2 = np.array([[12,43,74],
        [5,8,3],
        [8,9,9]])

Matsum = np.transpose(mat1)
Matsum

array([[ 1,  7,  8],
       [ 4,  5,  5],
       [ 6, 88, 77]])

In [18]:
# 4. Write a Python Program to Sort Words in Alphabetic Order?
def sort_words(words):
    sorted_words = sorted(words)
    return sorted_words

# Example words
words = ['apple', 'cherry','banana', 'elderberry' , 'date']

sorted_words = sort_words(words)

for word in sorted_words:
    print(word)


apple
banana
cherry
date
elderberry


In [1]:
# 5. Write a Python Program to Remove Punctuation From a String?
import re

def remove_punctuation(text):
    # Define the pattern to match punctuation
    punctuation_pattern = r'[^\w\s]'
    
    # Use the sub() function from the re module to replace punctuation with an empty string
    text_without_punctuation = re.sub(punctuation_pattern, '', text)
    
    return text_without_punctuation

input_text = "Hello, World! How are you today?"
clean_text = remove_punctuation(input_text)
print(clean_text)


Hello World How are you today
